services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=budgetdb'
      - 'MYSQL_PASSWORD=dev1234'
      - 'MYSQL_ROOT_PASSWORD=dev4321'
      - 'MYSQL_USER=apibudget'
    ports:
      - '3307:3306'
    volumes:
      - type: volume
      - source: budgetdb
      - target: /var/lib/mysql
volumes:
  budgetdb: