services:
  api_preprod:
    build:
      dockerfile: Dockerfile
    container_name: 'api_preprod'
    depends_on:
      - budgetdb
    entrypoint: 'java -jar /app.jar'
    ports:
      - '5000:5000'
    env_file: '.env'
    environment:
      - 'DATABASE_URL=jdbc:mysql://budgetdb:3306/budgetdb'
      - 'DATABASE_USERNAME=${DATABASE_USERNAME}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
      - 'SPRING_PROFILES_ACTIVE=preprod'
  budgetdb:
    image: 'mysql:8'
    container_name: 'budgetdb'
    env_file: '.env'
    environment:
      - 'MYSQL_DATABASE=budgetdb'
      - 'MYSQL_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DATABASE_USERNAME}'
    ports:
      - '3307:3306'
    volumes:
      - type: volume
        source: budgetdb
        target: /var/lib/mysql
volumes:
  budgetdb: