import { config } from "@fortawesome/fontawesome-svg-core";
import '@fortawesome/fontawesome-svg-core/styles.css';
import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import { Header } from "../components/header/Header";
import "./globals.css";
config.autoAddCss = false;

const inter = Lexend_Deca({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " flex min-h-screen flex-col items-center justify-between"}>
        <Header></Header>
        <main className="flex flex-col items-center py-12 mt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
